[package]
name = "DEWQ"
version = "0.1.0"
edition = "2021"

[lib]
name = "DEWQ"
path = "src/lib.rs"

[[bin]]
name = "DEWQ_run"
path = "src/main.rs"

[dependencies]
non_std = "0.1.4"

[features]
test_feature = []
