[package]
name = "DEWQ"
version = "0.0.4"
edition = "2021"
exclude = [
  "test.bmp"
]
description = "QR Code Generation Library"
license = "MIT OR Apache-2.0"

[lib]
name = "DEWQ"
path = "src/lib.rs"

[[bin]]
name = "DEWQ_run"
path = "src/main.rs"
